### ISSUE TITLE
Plugin changes "when"

### ISSUE THREAD

**Issue by ShmuelTreiger** [rvprasad/pytest-finer-verdicts#3]
Is there a reason you change when to "setup"? It's interfering with my custom plugin that needs when=call for logging purposes.

Otherwise seems to be a great plugin, thank you!

**Comment by rvprasad** [comment]
TBOMK `test_report.when` can only take on _setup, call,_ or _teardown_ values and an exception is treated as an error (not failure) only when `test_report.when != call`.  Hence, to use pytest framework with as little change as possible, this plugin sets `test_report.when` to `setup`.

If your plugin depends on the original value of `test_report.when`, then how about forcing your plugin to execute before this plugin via `pytest.hookimpl(tryFirst=True)`?

**Comment by ShmuelTreiger** [comment]
I think this is either a problem with pytest or with my understanding of pytest. Thank you for your help.
